version: '2'

networks:
  proxy:
    external: true
  internal:
    external: false

services:
  db_exam:
    container_name: postgres_exam
    image: postgres:alpine
    # build: ./postgres
    restart: always
    labels:
      - traefik.enable=false
    networks:
      - internal
    volumes:
      - /home/kubelab/data/exam_data:/var/lib/postgresql/data

  web_exam:
    container_name: web_exam
    build: ./sciproject
    command: sh /code/run.sh
    volumes:
      - ./sciproject:/code
    networks:
      - internal
      - proxy
    labels:
      - "traefik.frontend.rule=Host:exam.service.sci.tu.ac.th;PathPrefix:/"
      - traefik.backend=web_exam
      - traefik.port=80
      - traefik.docker.network=proxy
    depends_on:
      - db_exam

  nginx_exam:
      container_name: nginx_exam
      image: nginx:alpine
      volumes:
        - ./sciproject:/usr/share/nginx/html/
      labels:
        - traefik.enable=true
        - traefik.backend=nginx_exam
        - "traefik.frontend.rule=Host:exam.service.sci.tu.ac.th;PathPrefix:/static/,/media/"
        - traefik.docker.network=proxy
        - traefik.port=80
      networks:
        - internal
        - proxy
      depends_on:
        - web_exam
